Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   setup:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
@@ -15,7 +16,11 @@ jobs:
       - name: Install Docker
         run: |
           sudo apt-get update
-          sudo apt-get install -y docker.io 
+          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+          sudo apt-get update
+          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
           sudo systemctl start docker
           sudo systemctl enable docker
 
@@ -32,24 +37,13 @@ jobs:
   build:
     runs-on: ubuntu-latest
     needs: setup
+
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
-
-      - name: Build Docker Image
-        run: |
-          docker-compose -f ./data_app/docker-compose.yml build
-          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.event.repository.name }} -f ./data_app/Dockerfile ./data_app
-
-  sonar:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
 
       - name: SonarQube Analysis
         env:
@@ -63,34 +57,41 @@ jobs:
             -v "$(pwd):/usr/src" \
             sonarsource/sonar-scanner-cli
 
-  security-scan:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
+      - name: Build Docker Image
+        run: |
+          docker-compose -f ./data_app/docker-compose.yml build
+          docker build -t ${{ github.event.repository.name }} -f ./data_app/Dockerfile ./data_app
+
       - name: Security Image Scan
         run: |
+          docker run --rm \
+            -v /var/run/docker.sock:/var/run/docker.sock \
+            -v ${{ github.workspace }}:${{ github.workspace }} \
+            -w ${{ github.workspace }} \
+            aquasec/trivy image --exit-code 0 --severity HIGH,CRITICAL \
+            --format json \
+            --output trivy-report.html ${{ github.event.repository.name }}
+
           max_attempts=5
           attempt=1
+      
           while (( attempt <= max_attempts )); do
             echo "Attempt $attempt of $max_attempts..."
-            if docker run --rm \
-              -v /var/run/docker.sock:/var/run/docker.sock \
-              -v ${{ github.workspace }}:${{ github.workspace }} \
-              -w ${{ github.workspace }} \
-              aquasec/trivy image --exit-code 0 --severity HIGH,CRITICAL --format json ${{ github.event.repository.name }}; then
+            if docker run --rm aquasec/trivy image --exit-code 0 --severity HIGH,CRITICAL --format json ${{ github.event.repository.name }}; then
               echo "Trivy scan completed successfully."
               break
             else
               echo "Attempt $attempt failed. Retrying..."
               ((attempt++))
-              sleep 10
+              sleep 10 
             fi
           done
 
-  push:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
+          if (( attempt > max_attempts )); then
+            echo "Failed after $max_attempts attempts."
+            exit 1
+          fi
+
       - name: Push to Docker Hub
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
@@ -104,23 +105,24 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-    needs: push
+    needs: build
+
     steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
       - name: Deploy Application
         run: |
           docker-compose -f ./data_app/docker-compose.yml up -d
 
-  smoke-test:
-    runs-on: ubuntu-latest
-    needs: deploy
-    steps:
       - name: Smoke Test
         run: |
           docker run --rm -v ./postman:/etc/newman -t postman/newman run /etc/newman/${{ github.event.repository.name }}.json -r cli
 
-  upload-artifacts:
+  upload:
     runs-on: ubuntu-latest
-    needs: smoke-test
+    needs: deploy
+
     steps:
       - name: Upload Artifacts
         env:
